#pragma once

#include <QImage>
#include <QColor>
#include <QVector>

QImage getSeries1(double *data,
                  int start_col, int end_col,
                  double min_value, double max_value,
                  int image_width, int image_height,
                  QColor back_color = Qt::black, QColor point_color = Qt::red);

QImage getSeries2(double *data, int data_width,
                  int pick_row,
                  int start_col, int end_col,
                  double min_value, double max_value,
                  int image_width, int image_height,
                  QColor back_color = Qt::black, QColor point_color = Qt::red);

QImage getProfile2(double *data, int data_width,
                   int pick_col,
                   int start_row, int end_row,
                   double min_value, double max_value,
                   int image_width, int image_height,
                   QColor back_color = Qt::black, QColor point_color = Qt::red);

QImage getContour(double *data, int data_width,
                  int start_row, int end_row,
                  int start_col, int end_col,
                  double min_value, double max_value,
                  int image_width, int image_height,
                  const QVector<QColor> &color_bar = {QColor(0, 0, 143),
                                                      QColor(0, 0, 159),
                                                      QColor(0, 0, 175),
                                                      QColor(0, 0, 191),
                                                      QColor(0, 0, 207),
                                                      QColor(0, 0, 223),
                                                      QColor(0, 0, 239),
                                                      QColor(0, 0, 255),
                                                      QColor(0, 16, 255),
                                                      QColor(0, 32, 255),
                                                      QColor(0, 48, 255),
                                                      QColor(0, 64, 255),
                                                      QColor(0, 80, 255),
                                                      QColor(0, 96, 255),
                                                      QColor(0, 112, 255),
                                                      QColor(0, 128, 255),
                                                      QColor(0, 143, 255),
                                                      QColor(0, 159, 255),
                                                      QColor(0, 175, 255),
                                                      QColor(0, 191, 255),
                                                      QColor(0, 207, 255),
                                                      QColor(0, 223, 255),
                                                      QColor(0, 239, 255),
                                                      QColor(0, 255, 255),
                                                      QColor(16, 255, 239),
                                                      QColor(32, 255, 223),
                                                      QColor(48, 255, 207),
                                                      QColor(64, 255, 191),
                                                      QColor(80, 255, 175),
                                                      QColor(96, 255, 159),
                                                      QColor(112, 255, 143),
                                                      QColor(128, 255, 128),
                                                      QColor(143, 255, 112),
                                                      QColor(159, 255, 96),
                                                      QColor(175, 255, 80),
                                                      QColor(191, 255, 64),
                                                      QColor(207, 255, 48),
                                                      QColor(223, 255, 32),
                                                      QColor(239, 255, 16),
                                                      QColor(255, 255, 0),
                                                      QColor(255, 239, 0),
                                                      QColor(255, 223, 0),
                                                      QColor(255, 207, 0),
                                                      QColor(255, 191, 0),
                                                      QColor(255, 175, 0),
                                                      QColor(255, 159, 0),
                                                      QColor(255, 143, 0),
                                                      QColor(255, 128, 0),
                                                      QColor(255, 112, 0),
                                                      QColor(255, 96, 0),
                                                      QColor(255, 80, 0),
                                                      QColor(255, 64, 0),
                                                      QColor(255, 48, 0),
                                                      QColor(255, 32, 0),
                                                      QColor(255, 16, 0),
                                                      QColor(255, 0, 0),
                                                      QColor(239, 0, 0),
                                                      QColor(223, 0, 0),
                                                      QColor(207, 0, 0),
                                                      QColor(191, 0, 0),
                                                      QColor(175, 0, 0),
                                                      QColor(159, 0, 0),
                                                      QColor(143, 0, 0),
                                                      QColor(128, 0, 0)},
                  QColor back_color = Qt::black);
